package quiz_api.bo;

import org.junit.jupiter.api.Test;
import platine.zoo.quiz_api.bo.Quiz;

import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import static org.junit.jupiter.api.Assertions.assertNotNull;

public class QuizTest {
    @Test
    void quiz_shouldBeAnEntity(){
        assertNotNull(Quiz.class.getAnnotation(Entity.class));
    }

    @Test
    void quizId_shouldBeAnIdAndAutoGeneratedValue() throws NoSuchFieldException {
        assertNotNull(Quiz.class.getDeclaredField("id").getAnnotation(Id.class));
        assertNotNull(Quiz.class.getDeclaredField("id").getAnnotation(GeneratedValue.class));
    }

    @Test
    void questions_shouldBeAElementCollection() throws NoSuchFieldException {
        assertNotNull(Quiz.class.getDeclaredField("questions").getAnnotation(ElementCollection.class));
    }
}
